### ISSUE TITLE
Mini speech bubble & text quirks

### ISSUE THREAD

**Issue by Gawidev** [Tenome/Gurumin-Modding#1]
Hey there, recently started playing Gurumin, discovering this has been real cool, I love seeing documented records on investigations into a game's files.
Since I'm going to be playing the game with the eng script fix patch (& the JP dub), I'll keep an eye out for anything worth reporting back.
Although I guess worth noting, I am playing with the GOG version, and I'm not sure if that might produce any inconsistencies. If you know anything about that do let me know, otherwise I guess I'll be finding out.

First room of the game, inspecting the desk has unexpected behavior.
![its nice and neat](https://github.com/user-attachments/assets/3da90284-1ca6-4d75-994b-8eae49b67347)
Seems like the bubble is being dismissed instead of invoked.

A good bit later on, (after the first boss) in the dialogue where you return the sombrero to Pierre.
![Screenshot 2024-10-24 231927](https://github.com/user-attachments/assets/c047fabb-c4fd-4657-87e2-ee0d1b4dd835)
Looking at gameplay footage on youtube, it looks like commas/spaces got cut or something? not too sure...
![image](https://github.com/user-attachments/assets/194dab98-8b25-4531-b868-f44ba054000e)

Either way, thanks for the cool work 👍

**Comment by Tenome** [comment]
Thanks, I'll look into that. The desk was working when I tried it for this patch, but maybe I accidentally changed something. As for the comma, I most likely used a regular comma instead of a full-width comma there by mistake, so that's an easy fix.

I tried the desk again and it works as intended. Is this not popping up for you? This is with the 8.25.2024 patch version, Steam.

![322290_20241025164517_1](https://github.com/user-attachments/assets/c94d4d5f-a5ad-4933-9e89-8878e12d0f75)

**Comment by Gawidev** [comment]
> I tried the desk again and it works as intended. Is this not popping up for you? This is with the 8.25.2024 patch version, Steam.

This was before unlocking any of the wallpapers, so at the very start of a new game. Now that I've unlocked a couple, I'm getting the dialogue shown in your screenshot.

Also to possibly add a greater concern, it seems I've run into a hardlock this time.
![Screenshot 2024-10-25 225026](https://github.com/user-attachments/assets/f2b7dff2-1ea3-42c1-a581-a8e7c944bc8f)

Happens consistently, right at the start of the boulder dialog of all things
> "A giant rock?"
> "I have a ton of work, but I can't say no to a pretty lady."
```
Script error occurred (UPIPE)
Number of arguments is incorrect. (934)
```
I could make this its own issue if you would prefer, or keep stacking all I find here, whatever works best.

**Comment by Tenome** [comment]
It doesn't matter, here is fine. I'll look into that too. Do you have a save that you can upload for me? That's where I added a second bubble from the JP script, so perhaps I didn't format it correctly.

Comma: Fixed, needed a full-width comma
Desk when you don't have any wallpapers: Fixed, there was a `Message(0,"","","","");` that I accidentally dummied out.

**Comment by Gawidev** [comment]
Can do, is there perhaps another messaging platform that would be better suited e.g. discord or the likes.

**Comment by Tenome** [comment]
Github is fine, I need to keep track of the issues.

**Comment by Gawidev** [comment]
Understood, here's a save https://mega.nz/folder/5Ts3hY4R#zN8lyBRxMRv8kGLlV6tT-Q

**Comment by Tenome** [comment]
> Understood, here's a save https://mega.nz/folder/5Ts3hY4R#zN8lyBRxMRv8kGLlV6tT-Q

I might need the system.sav file too, I would just upload the entire folder.

**Comment by Gawidev** [comment]
Updated

**Comment by Tenome** [comment]
Sees to be fixed. Let me know if this works for you. https://github.com/Tenome/Gurumin-Modding/releases/tag/10.26.2024

Original: `Message(2,"Besides，if I refuse a digging request","I'd be a failure as a mole","");`
Fixed: `Message(2,"Besides， if I refuse a digging request，","I'd be a failure as a mole.","","");`

I have no experience with C programming, so I'm not sure why the end needed those extra quotes while the previous line ("can't say no to a pretty lady") only ends with `,"");` I suppose I should see if the other bubbles I added also have this issue. So you might encounter more.

**Comment by Gawidev** [comment]
Hmm interesting, Ill close this issue and create new ones dedicated to each new problem I report back with, just for the sake of consistency. I'll update the shared folder as I go. 

As for C, I am on the same boat as you, my uneducated guess would be some sort of overload? I think C has some weirdly specific manners with which it can achieve overloading but I wouldn't know how to determine if this was an example of it.
