### ISSUE TITLE
Script Error (Text in Japanese) when talking to mole to ask him to drill the boulder

### ISSUE THREAD

**Issue by Chrommanito** [Tenome/Gurumin-Modding#10]
told to visit the mole to open the path but after talking only got scripterror window that basically locks me from the rest of the game. I don't know if this is the base game or a problem with this mod.

**Comment by Tenome** [comment]
I need a save file, and ideally a screenshot/video.

**Comment by Chrommanito** [comment]
![GuruminBug](https://github.com/user-attachments/assets/517f01ff-1d98-4a08-b678-063fefad7d7b)

I'm sorry but where can I find the save directory of my Gurumin?

**Comment by Chrommanito** [comment]
[Savefile.zip](https://github.com/user-attachments/files/17692171/Savefile.zip)
is it in Appdata/Roaming/FALCOM ?

**Comment by Tenome** [comment]
I think that might be the same error that I fixed earlier (https://github.com/Tenome/Gurumin-Modding/issues/1#issuecomment-2439247736), so can you try the latest version if you're not on it? 

The saves are in
C:\Program Files (x86)\Steam\userdata\<ID>\322290\remote\
C:\Users\NAME\AppData\Roaming\FALCOM\GURUMIN\

**Comment by Chrommanito** [comment]
I'll go download the latest version too. In the mean time, here's my save file I pulled from AppData/Roaming/Falcom . Thanks for the fast reply!
[SaveFile.zip](https://github.com/user-attachments/files/17692388/SaveFile.zip)

**Comment by Chrommanito** [comment]
Ok the dialogue went through so it seems like the issue is solved. Thank you once again!
