### ISSUE TITLE
ScriptError (8030) Missing Pan dialog

### ISSUE THREAD

**Issue by Chrommanito** [Tenome/Gurumin-Modding#11]
![Untitled](https://github.com/user-attachments/assets/1d00b23f-50f2-449f-897d-3e1f58439530)
If I recall this happen before fighting fake Parin. Pan accuses Parin for stealing the cakes.

[SaveFile.zip](https://github.com/user-attachments/files/17779495/SaveFile.zip) (Save file slot 1)

**Comment by Tenome** [comment]
@Chrommanito  Your zip doesn't contain the save file, just the config ini.

**Comment by Chrommanito** [comment]
seems like appdata doesn't have my save file

This one is from steam userdata [GuruminSave.zip](https://github.com/user-attachments/files/17798387/GuruminSave.zip)

the bug happened in save file 1

**Comment by Tenome** [comment]
Fixed it. Last line was missing an extra `."`. Still haven't looked up what that actually means in C.

Download this and replace it in the `bin` folder.

https://github.com/Tenome/Gurumin-Modding/blob/main/!English%20Script%20Fix/bin/map.itm
