### ISSUE TITLE
Missing whitespace?

### ISSUE THREAD

**Issue by Gawidev** [Tenome/Gurumin-Modding#4]
**Describe the bug**
Not sure if this is a script-level bug or what, I can't find footage of this part so I cant confirm.

**Screenshots**
![Screenshot 2024-10-31 173902](https://github.com/user-attachments/assets/868cc073-8647-4b5d-b297-b8e931b0d823)

**Save file**
Updated in case you actually want to dodge those lasers https://mega.nz/#fm/dS83DZYb

**Comment by Tenome** [comment]
It does look like they forgot the whitespace in at least one of the lines.

![image](https://github.com/user-attachments/assets/c161a932-30dd-42ce-960c-a5ef9781c510)
