### ISSUE TITLE
whitespace missing

### ISSUE THREAD

**Issue by Gawidev** [Tenome/Gurumin-Modding#6]
**Describe the bug**
getting a feeling we're going to be seeing this one again...

**Screenshots**
![Screenshot 2024-10-31 203809](https://github.com/user-attachments/assets/efd4d87b-49f4-4f39-9664-c28783e38063)
Crown equip item description

**Save file**
[save 221](https://mega.nz/#fm/dS83DZYb)

**Comment by Tenome** [comment]
Same as the other issue, I can't modify item descriptions (10shop) since they're part of the .exe.

**Comment by Gawidev** [comment]
Ah, so specifically item stat info. I see, unlucky.
