### ISSUE TITLE
Long

### ISSUE THREAD

**Issue by Gawidev** [Tenome/Gurumin-Modding#7]
**Describe the bug**
Long <sub><sup>~~_live mister afro_~~</sup></sub>

**Screenshots**
![Screenshot 2024-10-31 215208](https://github.com/user-attachments/assets/c2a0407a-1d2d-4a51-bd5f-0d9f423f48fa)

**Save file**
[225](https://mega.nz/#fm/dS83DZYb)

**Comment by Tenome** [comment]
Ah, whitespace issue. Sometimes it lets you go without the full-width space `　`, sometimes it doesn't. I'll update the new descriptions.
[map.itm.txt](https://github.com/user-attachments/files/17595274/map.itm.txt)

**Comment by Gawidev** [comment]
I see, so just out of curiosity, would you say that using half-width characters when possible is more reliable?
