### ISSUE TITLE
Broken dialogue In Ruby Cave

### ISSUE THREAD

**Issue by Gawidev** [Tenome/Gurumin-Modding#9]
**Describe the bug**
Happens when you succeed or fail the password check.

**Screenshots**
![image](https://github.com/user-attachments/assets/27ef4d31-4061-4876-b514-7120c8131859)

**Save file**
[save 229](https://mega.nz/folder/5Ts3hY4R#zN8lyBRxMRv8kGLlV6tT-Q)

**Comment by Tenome** [comment]
I'll fix that in a bit. I suppose I should be thankful that the only issues you're encountering are the ones where I was experimenting with new bubbles, etc.

**Comment by Tenome** [comment]
Ah, I see what happened. I labeled it as a `string txt` instead of a `string type` because I was copy-pasting from the door password, which does use `txt.`
